- include_tasks:
    file: tune-shell.yml
    apply:
      tags: tune-shell
  tags: tune-shell

- include_tasks:
    file: dist-upgrade.yml
    apply:
      tags: dist-upgrade
  tags:
    - dist-upgrade
    - never

- include_tasks:
    file: install-packages.yml
    apply:
      tags: install-packages
  tags: install-packages