- name: Gather information about all Security Group
  ec2_group_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
  register: all_sg

- name: Delete Security Groups in VPC {{ vpc_info.vpcs[0].vpc_id }} by ID
  amazon.aws.ec2_group:
    region: "{{ ec2_region }}"
    group_id: "{{ item.group_id }}"
    state: absent
  loop: "{{ all_sg.security_groups }}"
  when: item.group_name != "default"