---
# not tested yet
- name : Create User Group
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_groups }}"

- name : Create a user
  user:
    name: "{{item.name}}"
    create_home: yes
    group: "{{item.group}}"
    state: present
    ssh_key_file: "{{ item.file_ssh_key }}"
    ssh_key_type: "{{ item.type_ssh_key }}"
  loop: "{{ user_info }}"

- name: Add SSH authorized key to host
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '{{ item.ssh_key_dest }}')}}"
  loop: "{{ user_info }}"
