- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages for Docker
  apt: name={{ docker_required_packages }} state=latest update_cache=yes

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install Docker
  apt: name={{ docker_packges }} state=latest update_cache=yes

- name: Install Python Docker module
  pip:
    name: 
    - docker
    - boto3
    - docker-compose

- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x

- name: Ensure appplication source code is cloned
  git:
    repo: "{{ repository }}"
    dest: "{{ application_path }}"

- name: Create and start services
  environment:
    - BOT_SLACK_TOKEN: "{{ bot_slack_token }}"
    - APP_SLACK_TOKEN: "{{ app_slack_token }}"
    - SIGNING_SLACK_SECRET: "{{ signing_slack_secret }}"
  docker_compose:
    project_src: "{{ application_path }}"